# Gitleaks configuration for Alice v2
# Ignore false positives in documentation

title = "Alice v2 Gitleaks Config"

# Disable problematic rules for documentation
[[rules]]
description = "Disable curl auth header detection in docs"
id = "curl-auth-header"
enabled = false

# Allowlist for documentation files
[allowlist]
description = "Documentation and test fixtures"
paths = [
    "README.md",
    "docs/",
    ".*\\.md$"
]
regexes = [
    "YOUR_API_KEY_HERE",
    "test-key-123",
    "fake-key-for-ci", 
    "Bearer test-",
    "example-token"
]