# Gitleaks configuration for Alice v2
# Ignore false positives in documentation

title = "Alice v2 Gitleaks Config"

# Disable problematic rules for documentation
[[rules]]
description = "Disable curl auth header detection in docs"
id = "curl-auth-header"
enabled = false

# Allowlist for documentation files
[allowlist]
description = "Documentation and test fixtures"
paths = [
    "README.md",
    "docs/",
    ".*\\.md$",
    ".github/workflows/.*\\.yml$"
]
regexes = [
    "YOUR_API_KEY_HERE",
    "test-key-123",
    "fake-key-for-ci",
    "fake-key-for-eval", 
    "Bearer test-",
    "example-token",
    "OPENAI_API_KEY=fake-key-for-ci",
    "N8N_ENCRYPTION_KEY=fake-key-for-ci-testing"
]