
services:
  guardian:
    build:
      context: ./services/guardian
      dockerfile: Dockerfile
    container_name: alice-guardian
    restart: unless-stopped
    init: true
    tty: false
    stdin_open: false
    stop_grace_period: 15s
    environment:
      - GUARD_RAM_SOFT=0.80
      - GUARD_RAM_HARD=0.92
      - GUARD_RECOVER_RAM=0.70
      - GUARD_CPU_SOFT=0.80
      - GUARD_TEMP_C_HARD=85
      - GUARD_BATTERY_PCT_HARD=25
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s

  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    container_name: alice-orchestrator
    depends_on:
      guardian:
        condition: service_healthy
    restart: unless-stopped
    init: true
    tty: false
    stdin_open: false
    stop_grace_period: 15s
    environment:
      - API_BASE=http://orchestrator:8000
      - GUARDIAN_HEALTH_URL=http://guardian:8787/health
      - LOG_DIR=/data/telemetry
      - OLLAMA_HOST=http://ollama:11434
      - SECURITY_ENFORCE=true
    volumes:
      - ./data/telemetry:/data/telemetry
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 15s

  loadgen:
    build:
      context: ./services/loadgen
      dockerfile: Dockerfile
    container_name: alice-loadgen
    depends_on:
      orchestrator:
        condition: service_started
      guardian:
        condition: service_healthy
    environment:
      - API_BASE=http://orchestrator:8000
      - GUARD_HEALTH=http://guardian:8787/health
      - SLO_BROWNOUT_TRIGGER_MS=150
      - RECOVER_S=60
      - MEMORY_BALLOON_GB=4
      - CPU_THREADS=4
      - DEEP_CONCURRENCY=2
    volumes:
      - ./data/telemetry:/data/telemetry
    restart: "no"
    profiles:
      - loadtest

  eval:
    build:
      context: ./services/eval
      dockerfile: Dockerfile
    container_name: alice-eval
    depends_on:
      orchestrator:
        condition: service_started
      guardian:
        condition: service_healthy
    environment:
      - API_BASE=http://orchestrator:8000
    volumes:
      - ./data/tests:/data/tests
    restart: "no"
    profiles:
      - eval

  dashboard:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    container_name: alice-dashboard
    restart: unless-stopped
    init: true
    tty: false
    stdin_open: false
    stop_grace_period: 15s
    volumes:
      - ./data:/data
    profiles:
      - dashboard
    ports:
      - "8501:8501"

  dev-proxy:
    image: caddy:2
    container_name: alice-dev-proxy
    depends_on:
      orchestrator:
        condition: service_healthy
      guardian:
        condition: service_healthy
    ports:
      - "18000:80"
    volumes:
      - ./ops/Caddyfile:/etc/caddy/Caddyfile:ro
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: alice-ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 30

  nlu:
    build:
      context: ./
      dockerfile: services/nlu/Dockerfile
    container_name: alice-nlu
    restart: unless-stopped
    environment:
      - NLU_LANG=sv
      - NLU_SIM_THRESH=0.62
      - NLU_MARGIN_MIN=0.06
      - NLU_XNLI_ENABLE=false
      - E5_ONNX_PATH=/models/e5-small.onnx
      - E5_TOKENIZER_JSON=/models/e5-tokenizer.json
      # XNLI avstängt tills ONNX finns
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9002/health"]
      interval: 10s
      timeout: 3s
      retries: 20
    volumes:
      - ./models:/models:ro

  curator:
    build:
      context: ./
      dockerfile: services/curator/Dockerfile
    container_name: alice-curator
    environment:
      - LOG_DIR=/data/telemetry
      - DATASETS_DIR=/data/datasets
    volumes:
      - ./data/telemetry:/data/telemetry
      - ./data/datasets:/data/datasets
    profiles:
      - curator

  scheduler:
    image: browt/supercronic:latest
    container_name: alice-scheduler
    restart: unless-stopped
    depends_on:
      orchestrator:
        condition: service_started
    volumes:
      - ./ops/schedule.cron:/etc/crontab:ro
      - ./:/workspace
      - ./logs:/workspace/logs
      - ./data:/workspace/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  telemetry_data:
    driver: local
  ollama:
    driver: local