# T9 Real Data Adapter – källor och fönster
window:
  lookback_hours: 48         # använd senaste 48h
  max_events: 20000
  min_triples: 100           # krävs för stabil eval, annars fallback till syntetiskt
sources:
  # Primär: färdigbyggda A/B/C-triples (maskade) om ni har dem
  - type: "file"
    path: "data/logs/ab_triples.ndjson"
  # Sekundär: härleder pseudo-triples från prod_responses (baseline vs adapter)
  - type: "file"
    path: "data/logs/prod_responses.ndjson"
fields:
  # Fält i ab_triples.ndjson (om finns)
  triple_prompt: "prompt"
  triple_candidates: "candidates"     # list[{id,text}]
  triple_winner: "winner_id"

  # Fält i prod_responses.ndjson (fallback)
  prompt: "prompt"
  answer: "answer"
  route: "route"                      # ex "baseline"/"adapter"
  ts: "ts"                            # valfritt (unix/iso), annars nu
  convo_id: "conversation_id"         # valfritt; fallback: hash(prompt)
pii:
  snippet_max_chars: 220
  redact:
    - "\\b\\d{6}-\\d{4}\\b"           # personnummer SE
    - "\\b\\d{3}-\\d{2}-\\d{4}\\b"    # US SSN
    - "\\b[\\w\\.-]+@[\\w\\.-]+\\.\\w+\\b"
    - "\\+?\\d[\\d\\s\\-]{6,}\\d"
    - "https?://\\S+"
output:
  triples_path: "data/rl/prefs/t9/triples_real.jsonl"