groups:
  - name: alice_v2_alerts
    rules:
      # Guardian Service Alerts
      - alert: GuardianUnreachable
        expr: up{job="alice_guardian"} == 0
        for: 5m
        labels:
          severity: critical
          service: guardian
        annotations:
          summary: "Guardian service is unreachable"
          description: "Guardian service has been down for more than 5 minutes. This affects system safety monitoring."

      - alert: GuardianHighRAM
        expr: alice_guardian_ram_pct > 90
        for: 2m
        labels:
          severity: warning
          service: guardian
        annotations:
          summary: "Guardian RAM usage is high"
          description: "Guardian service RAM usage is {{ $value }}%"

      # Orchestrator Service Alerts
      - alert: OrchestratorHighLatency
        expr: alice_orchestrator_p95_ms > 1000
        for: 2m
        labels:
          severity: warning
          service: orchestrator
        annotations:
          summary: "Orchestrator P95 latency is high"
          description: "Orchestrator P95 latency is {{ $value }}ms"

      - alert: OrchestratorHighErrorRate
        expr: rate(alice_orchestrator_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
          service: orchestrator
        annotations:
          summary: "Orchestrator error rate is high"
          description: "Orchestrator error rate is {{ $value | humanizePercentage }}"

      # System Health Alerts
      - alert: SystemDegraded
        expr: alice_system_health_score < 70
        for: 2m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "System health score is degraded"
          description: "System health score is {{ $value }}/100"

      - alert: SystemCritical
        expr: alice_system_health_score < 50
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "System health score is critical"
          description: "System health score is {{ $value }}/100 - immediate attention required"
