name: Cleanup Artifacts

on:
  schedule:
    - cron: '30 13 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Dry-run cleanup
        run: |
          DRY_RUN=true CLEANUP_CONFIRM=false bash scripts/cleanup.sh
      - name: Upload cleanup log
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-log
          path: logs/cleanup.log

