name: Docs Language Check

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  check-english:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docs language check (no Swedish)
        run: |
          python3 scripts/docs_language_check.py
