name: Nightly + 14:00 SLO Gate
on:
  schedule:
    - cron: '0 0 * * *' # 00:00 UTC nightly
    - cron: '0 12 * * *' # 12:00 UTC ≈ 14:00 CET/CEST
  workflow_dispatch:

jobs:
  slo-verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python & Node
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Fetch models (no commit)
        run: bash ./scripts/fetch_models.sh

      - name: Docker build & up
        run: |
          docker compose -f docker-compose.yml up -d --build
          ./scripts/wait-health.sh http://localhost:8000/health 30

      - name: Smoke status (should be 200 even if Guardian down)
        run: |
          curl -sSf http://localhost:8000/api/status/simple | jq .

      - name: Run auto verify (E2E + SLO gate)
        run: |
          chmod +x ./scripts/auto_verify.sh
          ./scripts/auto_verify.sh
        # auto_verify.sh ska exit 1 vid SLO- eller pass-rate-brott

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: telemetry-and-results
          path: |
            data/tests/**
            data/telemetry/**

      - name: Docker down
        if: always()
        run: docker compose down --volumes --remove-orphans
