name: Repo Health

on:
  pull_request:
    branches: [main, master, develop]

jobs:
  structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run repo health check
        run: |
          python3 scripts/repo_health.py
