name: T8 Nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  t8-offline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Drift watch (PSI/KS/Verifier)
        run: |
          python services/rl/drift/drift_watch.py || exit 1
      - name: Report
        run: echo "T8 nightly complete."