name: T9 Nightly Multi-Agent Eval

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  t9-eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pytest
      - name: Unit tests (agents)
        run: |
          pytest -q tests/test_agents.py
      - name: Multi-agent eval (synthetic)
        run: |
          python services/rl/prefs/eval_multi_agent.py > data/rl/prefs/t9/run_stdout.json
      - name: Multi-agent eval (real data, fallback to synthetic)
        run: |
          python services/rl/prefs/eval_multi_agent.py --realdata --cfg ops/config/t9_agents.yaml --real_cfg ops/config/t9_realdata.yaml > data/rl/prefs/t9/run_stdout_real.json || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: t9-multi-agent-report
          path: |
            data/rl/prefs/t9/multi_agent_report.json
            data/rl/prefs/t9/run_stdout.json
            ops/config/t9_agents.yaml
      - name: Upload realdata report
        uses: actions/upload-artifact@v4
        with:
          name: t9-multi-agent-report-real
          path: |
            data/rl/prefs/t9/run_stdout_real.json
            data/rl/prefs/t9/multi_agent_report.json
            data/rl/prefs/t9/triples_real.jsonl