name: TS Lint & Typecheck

on:
  push:
    branches: [main, master, develop, feat/**]
  pull_request:
    branches: [main, master, develop]

jobs:
  ts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        run: npm i -g pnpm@8.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
      - name: Lint web/packages
        run: pnpm run lint || true
      - name: Type-check web/packages
        run: pnpm run type-check || true
