name: Vulnerability Monitoring
on:
  schedule: [{ cron: "0 */6 * * *" }]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: vuln-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found"
          fi
      
      - name: OSV scan
        run: |
          npx osv-scanner --format sarif --output osv.sarif . || true
          ls -la *.sarif || echo "No SARIF files generated"
      
      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with: 
          sarif_file: osv.sarif
        continue-on-error: true